# Generated by Django 5.0.6 on 2024-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('motivations', models.JSONField()),
            ],
        ),
    ]
