# Generated by Django 5.0.6 on 2024-06-05 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('produccion', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('equipo_artistico', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, default='example@example.com', max_length=254, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio_aledano', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, null=True)),
                ('perfil_ocupacional', models.CharField(blank=True, max_length=50, null=True)),
                ('vinculacion_teatral', models.CharField(blank=True, max_length=50, null=True)),
                ('motivations', models.JSONField(blank=True, null=True)),
                ('otras_motivaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('medio_informacion', models.CharField(blank=True, default='Desconocido', max_length=50, null=True)),
                ('otros_eventos', models.JSONField(blank=True, default=list, null=True)),
                ('comprension_datos', models.BooleanField(default=True)),
                ('politica_datos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=255)),
                ('aforo', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulep', models.CharField(blank=True, max_length=10, null=True)),
                ('date_time', models.DateTimeField()),
                ('available_tickets', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='teatro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.theater'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('check_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.eventdate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.person')),
            ],
        ),
    ]
