# Generated by Django 5.0.6 on 2024-06-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='edad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
