# Generated by Django 5.0.6 on 2024-06-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='attended',
            new_name='check_in',
        ),
    ]
