# Generated by Django 5.0.6 on 2024-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_function_surveyresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
