# Generated by Django 5.0.6 on 2024-06-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_person_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='perfil_ocupacional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
