# Generated by Django 5.0.6 on 2024-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveyresponse_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='correo',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='medio_informacion',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='nivel_educativo',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='otros_eventos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='perfil_ocupacional',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='vinculacion_teatral',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
