# Generated by Django 5.0.6 on 2024-06-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_event_reserver_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nombre_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pulep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
