# Generated by Django 5.0.6 on 2024-05-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveyresponse_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='medio_informacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='motivations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='otros_eventos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='perfil_ocupacional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='vinculacion_teatral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
