# Generated by Django 5.0.6 on 2024-06-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_event_nombre_evento_event_pulep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pulep',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='equipo_artistico',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='produccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='comprension_datos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='politica_datos',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulep', models.CharField(blank=True, max_length=10, null=True)),
                ('date_time', models.DateTimeField()),
                ('available_tickets', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.eventdate'),
        ),
    ]
