# Generated by Django 5.0.6 on 2024-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_surveyresponse_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='comprension_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='politica_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='correo',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='medio_informacion',
            field=models.CharField(blank=True, default='Desconocido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='otros_eventos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
