# Generated by Django 5.0.6 on 2024-05-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveyresponse_otras_motivaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
