# Generated by Django 5.0.6 on 2024-05-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_function_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='date',
            new_name='date_time',
        ),
    ]
